import 'package:flutter/material.dart';

class Task6 extends StatefulWidget {
  const Task6({super.key});

  @override
  State<Task6> createState() => _Task6State();
}

class _Task6State extends State<Task6> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Task 6"),
        backgroundColor: Colors.teal,
        centerTitle: true,
      ),
      body: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          CircleAvatar(
            radius: 50,
            backgroundImage: NetworkImage(
              "https://img.freepik.com/premium-vector/cute-girl-avatar-cartoon-illustration-vector_1338461-953.jpg",
            ),
          ),
          Expanded(
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text("Vaishvi Gandhi",style: TextStyle(fontSize: 20,fontWeight: FontWeight.w600),),
                  ),
                  Text("This is the text for bio which is generated by me. https://img.freepik.com/premium-vector/cute-girl-avatar-cartoon-illustration-vector_1338461-953.jpg")]),
          ),
        ],
      ),
    );
  }
}
